# Generated by Django 4.1.3 on 2025-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('member_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_address', models.CharField(max_length=100)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
