# Generated by Django 4.1.3 on 2025-05-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manager_id', models.CharField(max_length=10)),
                ('branch_address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='issued_status',
            fields=[
                ('issued_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('issued_book_isbn', models.CharField(max_length=20)),
                ('issued_book_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='book_title',
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='return_status',
            fields=[
                ('return_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('issued', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.issued_status')),
            ],
        ),
        migrations.AddField(
            model_name='issued_status',
            name='issued_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.books'),
        ),
        migrations.AddField(
            model_name='issued_status',
            name='issued_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.employees'),
        ),
        migrations.AddField(
            model_name='issued_status',
            name='issued_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.members'),
        ),
    ]
