# Generated by Django 4.1.3 on 2025-04-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manager_id', models.CharField(max_length=10)),
                ('branch_address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='issued_status',
            fields=[
                ('issued_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('issued_book_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('issued_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.books')),
                ('issued_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.employees')),
                ('issued_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.members')),
            ],
        ),
        migrations.CreateModel(
            name='return_status',
            fields=[
                ('return_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('issued', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.issued_status')),
            ],
        ),
    ]
