# Generated by Django 4.1.3 on 2025-05-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_core', '0003_branch_employees_issued_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isbn', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History')], default='education', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('issuedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(default=library_core.models.get_expiry)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='issued_status',
            name='issued_book',
        ),
        migrations.RemoveField(
            model_name='issued_status',
            name='issued_emp',
        ),
        migrations.RemoveField(
            model_name='issued_status',
            name='issued_member',
        ),
        migrations.RemoveField(
            model_name='return_status',
            name='issued',
        ),
        migrations.DeleteModel(
            name='books',
        ),
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='employees',
        ),
        migrations.DeleteModel(
            name='issued_status',
        ),
        migrations.DeleteModel(
            name='members',
        ),
        migrations.DeleteModel(
            name='return_status',
        ),
    ]
