# Generated by Django 4.1.3 on 2025-05-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0003_branch_employees_issued_status_return_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='book_title',
        ),
    ]
