# Generated by Django 4.1.3 on 2025-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0004_rename_title_books_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
