# Generated by Django 4.1.3 on 2025-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='branch',
        ),
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20),
        ),
    ]
