# Generated by Django 5.2.1 on 2025-05-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0006_alter_book_author_alter_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library_core.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library_core.studentextra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='enrollment',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
