# Generated by Django 4.1.3 on 2025-05-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0006_remove_employees_branch_employees_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
    ]
