# Generated by Django 4.1.3 on 2025-05-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0007_remove_employees_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='branch_id',
            field=models.ForeignKey(default='B001', on_delete=django.db.models.deletion.CASCADE, to='library_core.branch'),
            preserve_default=False,
        ),
    ]
