# Generated by Django 4.1.3 on 2025-05-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0008_employees_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
