# Generated by Django 4.1.3 on 2025-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0009_rename_branch_id_employees_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_status',
            name='issued_book_isbn',
            field=models.CharField(default='0000000000000', max_length=13),
            preserve_default=False,
        ),
    ]
