# Generated by Django 4.1.3 on 2025-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0010_issued_status_issued_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_status',
            name='issued_book_isbn',
            field=models.CharField(max_length=20),
        ),
    ]
