# Generated by Django 4.1.3 on 2025-05-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_core', '0011_alter_issued_status_issued_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='ADMIN', max_length=20),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('member_address', models.CharField(max_length=100)),
                ('reg_date', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='issued_status',
            name='issued_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.member'),
        ),
        migrations.DeleteModel(
            name='members',
        ),
    ]
