# Generated by Django 4.1.3 on 2025-05-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0012_remove_employees_emp_name_employees_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('member_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_address', models.CharField(max_length=100)),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='issued_status',
            name='issued_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_core.members'),
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
