# Generated by Django 4.1.3 on 2025-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0013_members_remove_employees_user_employees_emp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
